#!/bin/bash
cd "C:/Users/info/the420code"

do_lang() {
  local L=$1; shift
  local F="$L/index.html"
  while [ $# -ge 2 ]; do
    local EN="$1"; local TR="$2"; shift 2
    sed -i "s|ap-tag\">$EN</span>|ap-tag\">$TR</span>|g" "$F"
  done
  echo "  $L done"
}

do_lang fr "Mathematics" "Mathématiques" "Foundations" "Fondements" "Logic" "Logique" "Relativity" "Relativité" "Symmetry Breaking" "Brisure de symétrie" "Dimensionality" "Dimensionnalité" "General Relativity" "Relativité générale" "Quantum Foundations" "Fondements quantiques" "Hilbert Space" "Espace de Hilbert" "Spin" "Spin" "Uncertainty" "Incertitude" "Decoherence" "Décohérence" "Born Rule" "Règle de Born" "Entanglement" "Intrication" "Fine Structure" "Structure fine" "Electromagnetism" "Électromagnétisme" "Gauge Structure" "Structure de jauge" "Electroweak" "Électrofaible" "Strong Force" "Force forte" "Unification" "Unification" "Quantum Gravity" "Gravité quantique" "Gravity" "Gravité" "Mass" "Masse" "Antimatter" "Antimatière" "Baryon Asymmetry" "Asymétrie baryonique" "Rotation Curves" "Courbes de rotation" "Acceleration Scale" "Échelle d'accélération" "Dark Energy" "Énergie noire" "Structure Formation" "Formation de structures" "Cosmology" "Cosmologie" "Cyclic Cosmology" "Cosmologie cyclique" "Consciousness" "Conscience" "Religion" "Religion" "Agency" "Agentivité" "Death" "Mort" "AI Alignment" "Alignement de l'IA" "Justice" "Justice" "Bioethics" "Bioéthique" "Drug Policy" "Politique des drogues" "Economics" "Économie" "Biology" "Biologie" "The Body" "Le Corps"

do_lang de "Mathematics" "Mathematik" "Foundations" "Grundlagen" "Logic" "Logik" "Relativity" "Relativität" "Symmetry Breaking" "Symmetriebrechung" "Dimensionality" "Dimensionalität" "General Relativity" "Allgemeine Relativität" "Quantum Foundations" "Quantengrundlagen" "Hilbert Space" "Hilbertraum" "Spin" "Spin" "Uncertainty" "Unschärfe" "Decoherence" "Dekohärenz" "Born Rule" "Born-Regel" "Entanglement" "Verschränkung" "Fine Structure" "Feinstruktur" "Electromagnetism" "Elektromagnetismus" "Gauge Structure" "Eichstruktur" "Electroweak" "Elektroschwach" "Strong Force" "Starke Kraft" "Unification" "Vereinigung" "Quantum Gravity" "Quantengravitation" "Gravity" "Gravitation" "Mass" "Masse" "Antimatter" "Antimaterie" "Baryon Asymmetry" "Baryonenasymmetrie" "Rotation Curves" "Rotationskurven" "Acceleration Scale" "Beschleunigungsskala" "Dark Energy" "Dunkle Energie" "Structure Formation" "Strukturbildung" "Cosmology" "Kosmologie" "Cyclic Cosmology" "Zyklische Kosmologie" "Consciousness" "Bewusstsein" "Religion" "Religion" "Agency" "Handlungsfähigkeit" "Death" "Tod" "AI Alignment" "KI-Alignment" "Justice" "Gerechtigkeit" "Bioethics" "Bioethik" "Drug Policy" "Drogenpolitik" "Economics" "Wirtschaft" "Biology" "Biologie" "The Body" "Der Körper"

do_lang pt "Mathematics" "Matemática" "Foundations" "Fundamentos" "Logic" "Lógica" "Relativity" "Relatividade" "Symmetry Breaking" "Quebra de simetria" "Dimensionality" "Dimensionalidade" "General Relativity" "Relatividade geral" "Quantum Foundations" "Fundamentos quânticos" "Hilbert Space" "Espaço de Hilbert" "Spin" "Spin" "Uncertainty" "Incerteza" "Decoherence" "Decoerência" "Born Rule" "Regra de Born" "Entanglement" "Emaranhamento" "Fine Structure" "Estrutura fina" "Electromagnetism" "Eletromagnetismo" "Gauge Structure" "Estrutura gauge" "Electroweak" "Eletrofraco" "Strong Force" "Força forte" "Unification" "Unificação" "Quantum Gravity" "Gravidade quântica" "Gravity" "Gravidade" "Mass" "Massa" "Antimatter" "Antimatéria" "Baryon Asymmetry" "Assimetria bariônica" "Rotation Curves" "Curvas de rotação" "Acceleration Scale" "Escala de aceleração" "Dark Energy" "Energia escura" "Structure Formation" "Formação de estruturas" "Cosmology" "Cosmologia" "Cyclic Cosmology" "Cosmologia cíclica" "Consciousness" "Consciência" "Religion" "Religião" "Agency" "Agência" "Death" "Morte" "AI Alignment" "Alinhamento de IA" "Justice" "Justiça" "Bioethics" "Bioética" "Drug Policy" "Política de drogas" "Economics" "Economia" "Biology" "Biologia" "The Body" "O Corpo"

do_lang nl "Mathematics" "Wiskunde" "Foundations" "Grondslagen" "Logic" "Logica" "Relativity" "Relativiteit" "Symmetry Breaking" "Symmetriebreking" "Dimensionality" "Dimensionaliteit" "General Relativity" "Algemene relativiteit" "Quantum Foundations" "Kwantumgrondslagen" "Hilbert Space" "Hilbertruimte" "Spin" "Spin" "Uncertainty" "Onzekerheid" "Decoherence" "Decoherentie" "Born Rule" "Born-regel" "Entanglement" "Verstrengeling" "Fine Structure" "Fijnstructuur" "Electromagnetism" "Elektromagnetisme" "Gauge Structure" "IJkstructuur" "Electroweak" "Elektrozwak" "Strong Force" "Sterke kracht" "Unification" "Unificatie" "Quantum Gravity" "Kwantumzwaartekracht" "Gravity" "Zwaartekracht" "Mass" "Massa" "Antimatter" "Antimaterie" "Baryon Asymmetry" "Baryonasymmetrie" "Rotation Curves" "Rotatiekrommen" "Acceleration Scale" "Versnellingsschaal" "Dark Energy" "Donkere energie" "Structure Formation" "Structuurvorming" "Cosmology" "Kosmologie" "Cyclic Cosmology" "Cyclische kosmologie" "Consciousness" "Bewustzijn" "Religion" "Religie" "Agency" "Agentschap" "Death" "Dood" "AI Alignment" "AI-alignment" "Justice" "Rechtvaardigheid" "Bioethics" "Bio-ethiek" "Drug Policy" "Drugsbeleid" "Economics" "Economie" "Biology" "Biologie" "The Body" "Het Lichaam"

do_lang it "Mathematics" "Matematica" "Foundations" "Fondamenti" "Logic" "Logica" "Relativity" "Relatività" "Symmetry Breaking" "Rottura di simmetria" "Dimensionality" "Dimensionalità" "General Relativity" "Relatività generale" "Quantum Foundations" "Fondamenti quantistici" "Hilbert Space" "Spazio di Hilbert" "Spin" "Spin" "Uncertainty" "Indeterminazione" "Decoherence" "Decoerenza" "Born Rule" "Regola di Born" "Entanglement" "Entanglement" "Fine Structure" "Struttura fine" "Electromagnetism" "Elettromagnetismo" "Gauge Structure" "Struttura di gauge" "Electroweak" "Elettrodebole" "Strong Force" "Forza forte" "Unification" "Unificazione" "Quantum Gravity" "Gravità quantistica" "Gravity" "Gravità" "Mass" "Massa" "Antimatter" "Antimateria" "Baryon Asymmetry" "Asimmetria barionica" "Rotation Curves" "Curve di rotazione" "Acceleration Scale" "Scala di accelerazione" "Dark Energy" "Energia oscura" "Structure Formation" "Formazione di strutture" "Cosmology" "Cosmologia" "Cyclic Cosmology" "Cosmologia ciclica" "Consciousness" "Coscienza" "Religion" "Religione" "Agency" "Agency" "Death" "Morte" "AI Alignment" "Allineamento dell'IA" "Justice" "Giustizia" "Bioethics" "Bioetica" "Drug Policy" "Politica delle droghe" "Economics" "Economia" "Biology" "Biologia" "The Body" "Il Corpo"

do_lang zh "Mathematics" "数学" "Foundations" "基础" "Logic" "逻辑" "Relativity" "相对论" "Symmetry Breaking" "对称性破缺" "Dimensionality" "维度性" "General Relativity" "广义相对论" "Quantum Foundations" "量子基础" "Hilbert Space" "希尔伯特空间" "Spin" "自旋" "Uncertainty" "不确定性" "Decoherence" "退相干" "Born Rule" "玻恩规则" "Entanglement" "纠缠" "Fine Structure" "精细结构" "Electromagnetism" "电磁学" "Gauge Structure" "规范结构" "Electroweak" "电弱" "Strong Force" "强力" "Unification" "统一" "Quantum Gravity" "量子引力" "Gravity" "引力" "Mass" "质量" "Antimatter" "反物质" "Baryon Asymmetry" "重子不对称" "Rotation Curves" "旋转曲线" "Acceleration Scale" "加速度标度" "Dark Energy" "暗能量" "Structure Formation" "结构形成" "Cosmology" "宇宙学" "Cyclic Cosmology" "循环宇宙学" "Consciousness" "意识" "Religion" "宗教" "Agency" "能动性" "Death" "死亡" "AI Alignment" "AI 对齐" "Justice" "正义" "Bioethics" "生物伦理" "Drug Policy" "毒品政策" "Economics" "经济学" "Biology" "生物学" "The Body" "身体"

do_lang ja "Mathematics" "数学" "Foundations" "基礎" "Logic" "論理" "Relativity" "相対性" "Symmetry Breaking" "対称性の破れ" "Dimensionality" "次元性" "General Relativity" "一般相対性" "Quantum Foundations" "量子基礎" "Hilbert Space" "ヒルベルト空間" "Spin" "スピン" "Uncertainty" "不確定性" "Decoherence" "デコヒーレンス" "Born Rule" "ボルン規則" "Entanglement" "エンタングルメント" "Fine Structure" "微細構造" "Electromagnetism" "電磁気学" "Gauge Structure" "ゲージ構造" "Electroweak" "電弱" "Strong Force" "強い力" "Unification" "統一" "Quantum Gravity" "量子重力" "Gravity" "重力" "Mass" "質量" "Antimatter" "反物質" "Baryon Asymmetry" "バリオン非対称" "Rotation Curves" "回転曲線" "Acceleration Scale" "加速度スケール" "Dark Energy" "ダークエネルギー" "Structure Formation" "構造形成" "Cosmology" "宇宙論" "Cyclic Cosmology" "循環宇宙論" "Consciousness" "意識" "Religion" "宗教" "Agency" "エージェンシー" "Death" "死" "AI Alignment" "AIアラインメント" "Justice" "正義" "Bioethics" "生命倫理" "Drug Policy" "薬物政策" "Economics" "経済学" "Biology" "生物学" "The Body" "身体"

do_lang ko "Mathematics" "수학" "Foundations" "기초" "Logic" "논리" "Relativity" "상대성" "Symmetry Breaking" "대칭 깨짐" "Dimensionality" "차원성" "General Relativity" "일반 상대성" "Quantum Foundations" "양자 기초" "Hilbert Space" "힐베르트 공간" "Spin" "스핀" "Uncertainty" "불확정성" "Decoherence" "결어긋남" "Born Rule" "보른 규칙" "Entanglement" "얽힘" "Fine Structure" "미세구조" "Electromagnetism" "전자기학" "Gauge Structure" "게이지 구조" "Electroweak" "전약" "Strong Force" "강력" "Unification" "통일" "Quantum Gravity" "양자 중력" "Gravity" "중력" "Mass" "질량" "Antimatter" "반물질" "Baryon Asymmetry" "바리온 비대칭" "Rotation Curves" "회전 곡선" "Acceleration Scale" "가속도 척도" "Dark Energy" "암흑 에너지" "Structure Formation" "구조 형성" "Cosmology" "우주론" "Cyclic Cosmology" "순환 우주론" "Consciousness" "의식" "Religion" "종교" "Agency" "행위능력" "Death" "죽음" "AI Alignment" "AI 정렬" "Justice" "정의" "Bioethics" "생명윤리" "Drug Policy" "약물 정책" "Economics" "경제학" "Biology" "생물학" "The Body" "몸"

do_lang ru "Mathematics" "Математика" "Foundations" "Основы" "Logic" "Логика" "Relativity" "Относительность" "Symmetry Breaking" "Нарушение симметрии" "Dimensionality" "Размерность" "General Relativity" "Общая относительность" "Quantum Foundations" "Квантовые основы" "Hilbert Space" "Гильбертово пространство" "Spin" "Спин" "Uncertainty" "Неопределённость" "Decoherence" "Декогеренция" "Born Rule" "Правило Борна" "Entanglement" "Запутанность" "Fine Structure" "Тонкая структура" "Electromagnetism" "Электромагнетизм" "Gauge Structure" "Калибровочная структура" "Electroweak" "Электрослабое" "Strong Force" "Сильная сила" "Unification" "Объединение" "Quantum Gravity" "Квантовая гравитация" "Gravity" "Гравитация" "Mass" "Масса" "Antimatter" "Антиматерия" "Baryon Asymmetry" "Барионная асимметрия" "Rotation Curves" "Кривые вращения" "Acceleration Scale" "Шкала ускорения" "Dark Energy" "Тёмная энергия" "Structure Formation" "Формирование структур" "Cosmology" "Космология" "Cyclic Cosmology" "Циклическая космология" "Consciousness" "Сознание" "Religion" "Религия" "Agency" "Агентность" "Death" "Смерть" "AI Alignment" "Выравнивание ИИ" "Justice" "Справедливость" "Bioethics" "Биоэтика" "Drug Policy" "Наркополитика" "Economics" "Экономика" "Biology" "Биология" "The Body" "Тело"

do_lang ar "Mathematics" "الرياضيات" "Foundations" "الأسس" "Logic" "المنطق" "Relativity" "النسبية" "Symmetry Breaking" "كسر التناظر" "Dimensionality" "البُعدية" "General Relativity" "النسبية العامة" "Quantum Foundations" "أسس الكمّ" "Hilbert Space" "فضاء هيلبرت" "Spin" "اللَّف" "Uncertainty" "عدم اليقين" "Decoherence" "فقدان التماسك" "Born Rule" "قاعدة بورن" "Entanglement" "التشابك" "Fine Structure" "البنية الدقيقة" "Electromagnetism" "الكهرومغناطيسية" "Gauge Structure" "بنية المعيار" "Electroweak" "كهروضعيف" "Strong Force" "القوة القوية" "Unification" "التوحيد" "Quantum Gravity" "الجاذبية الكمّية" "Gravity" "الجاذبية" "Mass" "الكتلة" "Antimatter" "المادة المضادة" "Baryon Asymmetry" "عدم تناظر الباريونات" "Rotation Curves" "منحنيات الدوران" "Acceleration Scale" "مقياس التسارع" "Dark Energy" "الطاقة المظلمة" "Structure Formation" "تكوين البنى" "Cosmology" "علم الكونيات" "Cyclic Cosmology" "الكونيات الدورية" "Consciousness" "الوعي" "Religion" "الدين" "Agency" "الفاعلية" "Death" "الموت" "AI Alignment" "محاذاة الذكاء الاصطناعي" "Justice" "العدالة" "Bioethics" "أخلاقيات الأحياء" "Drug Policy" "سياسة المخدرات" "Economics" "الاقتصاد" "Biology" "الأحياء" "The Body" "الجسد"

do_lang hi "Mathematics" "गणित" "Foundations" "आधार" "Logic" "तर्क" "Relativity" "सापेक्षता" "Symmetry Breaking" "सममिति भंग" "Dimensionality" "आयामिता" "General Relativity" "सामान्य सापेक्षता" "Quantum Foundations" "क्वांटम आधार" "Hilbert Space" "हिल्बर्ट अवकाश" "Spin" "स्पिन" "Uncertainty" "अनिश्चितता" "Decoherence" "विसंबद्धता" "Born Rule" "बोर्न नियम" "Entanglement" "उलझाव" "Fine Structure" "सूक्ष्म संरचना" "Electromagnetism" "विद्युत चुम्बकत्व" "Gauge Structure" "गेज संरचना" "Electroweak" "विद्युतदुर्बल" "Strong Force" "प्रबल बल" "Unification" "एकीकरण" "Quantum Gravity" "क्वांटम गुरुत्व" "Gravity" "गुरुत्व" "Mass" "द्रव्यमान" "Antimatter" "प्रतिपदार्थ" "Baryon Asymmetry" "बैरियॉन विषमता" "Rotation Curves" "घूर्णन वक्र" "Acceleration Scale" "त्वरण पैमाना" "Dark Energy" "गहरी ऊर्जा" "Structure Formation" "संरचना निर्माण" "Cosmology" "ब्रह्मांड विज्ञान" "Cyclic Cosmology" "चक्रीय ब्रह्मांड विज्ञान" "Consciousness" "चेतना" "Religion" "धर्म" "Agency" "कर्तृत्व" "Death" "मृत्यु" "AI Alignment" "AI संरेखण" "Justice" "न्याय" "Bioethics" "जैवनैतिकता" "Drug Policy" "मादक द्रव्य नीति" "Economics" "अर्थशास्त्र" "Biology" "जीवविज्ञान" "The Body" "शरीर"

echo "All done"
