const fs = require('fs');
const path = require('path');
const LANGS = ['es','fr','de','pt','nl','it','zh','ja','ko','ru','ar','hi'];

// All replacements: [english_string, {lang: translation, ...}]
const R = [
  // === HEADLINE RESULTS labels ===
  ['<span class="result-label">Proton mass ratio</span>',{es:'Relación de masa del protón',fr:'Rapport de masse du proton',de:'Proton-Massen-Verhältnis',pt:'Razão de massa do próton',nl:'Proton-massaverhouding',it:'Rapporto di massa del protone',zh:'质子质量比',ja:'陽子質量比',ko:'양성자 질량비',ru:'Отношение масс протона',ar:'نسبة كتلة البروتون',hi:'प्रोटॉन द्रव्यमान अनुपात'}],
  ['<span class="result-label">Gravitational constant G</span>',{es:'Constante gravitacional G',fr:'Constante gravitationnelle G',de:'Gravitationskonstante G',pt:'Constante gravitacional G',nl:'Gravitatieconstante G',it:'Costante gravitazionale G',zh:'引力常数 G',ja:'重力定数 G',ko:'중력 상수 G',ru:'Гравитационная постоянная G',ar:'ثابت الجاذبية G',hi:'गुरुत्वाकर्षण स्थिरांक G'}],
  ['<span class="result-label">MOND acceleration a₀</span>',{es:'Aceleración MOND a₀',fr:'Accélération MOND a₀',de:'MOND-Beschleunigung a₀',pt:'Aceleração MOND a₀',nl:'MOND-versnelling a₀',it:'Accelerazione MOND a₀',zh:'MOND 加速度 a₀',ja:'MOND加速度 a₀',ko:'MOND 가속도 a₀',ru:'Ускорение MOND a₀',ar:'تسارع MOND a₀',hi:'MOND त्वरण a₀'}],
  ['<span class="result-label">Neutron-proton mass difference</span>',{es:'Diferencia de masa neutrón-protón',fr:'Différence de masse neutron-proton',de:'Neutron-Proton-Massendifferenz',pt:'Diferença de massa nêutron-próton',nl:'Neutron-proton-massaverschil',it:'Differenza di massa neutrone-protone',zh:'中子-质子质量差',ja:'中性子-陽子質量差',ko:'중성자-양성자 질량 차이',ru:'Разность масс нейтрон-протон',ar:'فرق كتلة النيوترون-البروتون',hi:'न्यूट्रॉन-प्रोटॉन द्रव्यमान अंतर'}],
  ['<span class="result-label">Visible matter fraction</span>',{es:'Fracción de materia visible',fr:'Fraction de matière visible',de:'Sichtbarer Materieanteil',pt:'Fração de matéria visível',nl:'Zichtbare-materiefractie',it:'Frazione di materia visibile',zh:'可见物质比例',ja:'可視物質割合',ko:'가시 물질 비율',ru:'Доля видимой материи',ar:'نسبة المادة المرئية',hi:'दृश्य पदार्थ अंश'}],
  ['<span class="result-label">Chiral coupling</span>',{es:'Acoplamiento quiral',fr:'Couplage chiral',de:'Chirale Kopplung',pt:'Acoplamento quiral',nl:'Chirale koppeling',it:'Accoppiamento chirale',zh:'手征耦合',ja:'キラル結合',ko:'카이랄 결합',ru:'Хиральная связь',ar:'الاقتران اللولبي',hi:'काइरल युग्मन'}],
  ['<span class="result-label">Three constants, three axioms</span>',{es:'Tres constantes, tres axiomas',fr:'Trois constantes, trois axiomes',de:'Drei Konstanten, drei Axiome',pt:'Três constantes, três axiomas',nl:'Drie constanten, drie axioma\'s',it:'Tre costanti, tre assiomi',zh:'三个常数，三条公理',ja:'三つの定数、三つの公理',ko:'세 상수, 세 공리',ru:'Три константы, три аксиомы',ar:'ثلاثة ثوابت، ثلاث بديهيات',hi:'तीन स्थिरांक, तीन स्वयंसिद्ध'}],

  // === HEADLINE RESULTS values ===
  ['0.69% of CODATA',{es:'0,69% de CODATA',fr:'0,69% de CODATA',de:'0,69% von CODATA',pt:'0,69% do CODATA',nl:'0,69% van CODATA',it:'0,69% di CODATA',zh:'CODATA 的 0.69%',ja:'CODATAの0.69%',ko:'CODATA의 0.69%',ru:'0,69% от CODATA',ar:'0.69% من CODATA',hi:'CODATA का 0.69%'}],
  ['0.3%, parameter-free',{es:'0,3%, sin parámetros',fr:'0,3%, sans paramètre',de:'0,3%, parameterfrei',pt:'0,3%, sem parâmetros',nl:'0,3%, parametervrij',it:'0,3%, senza parametri',zh:'0.3%，无参数',ja:'0.3%、パラメータフリー',ko:'0.3%, 매개변수 없음',ru:'0,3%, без параметров',ar:'0.3%، بلا معاملات',hi:'0.3%, पैरामीटर-मुक्त'}],
  ['Derived, KS-63 closed',{es:'Derivado, KS-63 cerrado',fr:'Dérivé, KS-63 fermé',de:'Abgeleitet, KS-63 geschlossen',pt:'Derivado, KS-63 fechado',nl:'Afgeleid, KS-63 gesloten',it:'Derivato, KS-63 chiuso',zh:'已推导，KS-63 已关闭',ja:'導出済み、KS-63 閉鎖',ko:'도출됨, KS-63 폐쇄',ru:'Выведено, KS-63 закрыт',ar:'مُشتق، KS-63 مُغلق',hi:'व्युत्पन्न, KS-63 बंद'}],

  // === ALSO DERIVED list ===
  ['N = 3 spatial dimensions (AP10)',{es:'N = 3 dimensiones espaciales (AP10)',fr:'N = 3 dimensions spatiales (AP10)',de:'N = 3 Raumdimensionen (AP10)',pt:'N = 3 dimensões espaciais (AP10)',nl:'N = 3 ruimtelijke dimensies (AP10)',it:'N = 3 dimensioni spaziali (AP10)',zh:'N = 3 个空间维度 (AP10)',ja:'N = 3 空間次元 (AP10)',ko:'N = 3 공간 차원 (AP10)',ru:'N = 3 пространственных измерения (AP10)',ar:'N = 3 أبعاد مكانية (AP10)',hi:'N = 3 स्थानिक आयाम (AP10)'}],
  ["Einstein's field equations (AP08)",{es:'Ecuaciones de campo de Einstein (AP08)',fr:"Équations de champ d'Einstein (AP08)",de:'Einsteins Feldgleichungen (AP08)',pt:'Equações de campo de Einstein (AP08)',nl:'Einsteins veldvergelijkingen (AP08)',it:'Equazioni di campo di Einstein (AP08)',zh:'爱因斯坦场方程 (AP08)',ja:'アインシュタインの場の方程式 (AP08)',ko:'아인슈타인 장 방정식 (AP08)',ru:'Уравнения поля Эйнштейна (AP08)',ar:'معادلات حقل آينشتاين (AP08)',hi:'आइंस्टीन की क्षेत्र समीकरण (AP08)'}],
  ['The Born rule (AP25)',{es:'La regla de Born (AP25)',fr:'La règle de Born (AP25)',de:'Die Born-Regel (AP25)',pt:'A regra de Born (AP25)',nl:'De Born-regel (AP25)',it:'La regola di Born (AP25)',zh:'玻恩规则 (AP25)',ja:'ボルン規則 (AP25)',ko:'보른 규칙 (AP25)',ru:'Правило Борна (AP25)',ar:'قاعدة بورن (AP25)',hi:'बोर्न नियम (AP25)'}],
  ['Standard Model gauge group SU(3)',{es:'Grupo gauge del Modelo Estándar SU(3)',fr:'Groupe de jauge du Modèle Standard SU(3)',de:'Eichgruppe des Standardmodells SU(3)',pt:'Grupo gauge do Modelo Padrão SU(3)',nl:'IJkgroep van het Standaardmodel SU(3)',it:'Gruppo di gauge del Modello Standard SU(3)',zh:'标准模型规范群 SU(3)',ja:'標準模型ゲージ群 SU(3)',ko:'표준 모형 게이지 군 SU(3)',ru:'Калибровочная группа Стандартной модели SU(3)',ar:'مجموعة المعيار للنموذج القياسي SU(3)',hi:'मानक मॉडल गेज समूह SU(3)'}],
  ['Chiral coupling — unexplained since 1956, now derived (AP16)',{es:'Acoplamiento quiral — sin explicación desde 1956, ahora derivado (AP16)',fr:'Couplage chiral — inexpliqué depuis 1956, maintenant dérivé (AP16)',de:'Chirale Kopplung — seit 1956 unerklärt, jetzt abgeleitet (AP16)',pt:'Acoplamento quiral — sem explicação desde 1956, agora derivado (AP16)',nl:'Chirale koppeling — onverklaard sinds 1956, nu afgeleid (AP16)',it:'Accoppiamento chirale — inspiegato dal 1956, ora derivato (AP16)',zh:'手征耦合——自1956年以来未解释，现已推导 (AP16)',ja:'キラル結合——1956年以来未解明、今導出 (AP16)',ko:'카이랄 결합 — 1956년 이래 미해명, 이제 도출됨 (AP16)',ru:'Хиральная связь — необъяснённая с 1956 г., теперь выведена (AP16)',ar:'الاقتران اللولبي — غير مُفسَّر منذ 1956، الآن مُشتق (AP16)',hi:'काइरल युग्मन — 1956 से अस्पष्ट, अब व्युत्पन्न (AP16)'}],
  ['Flat rotation curves without dark matter particles (AP17)',{es:'Curvas de rotación planas sin partículas de materia oscura (AP17)',fr:'Courbes de rotation plates sans particules de matière noire (AP17)',de:'Flache Rotationskurven ohne Dunkle-Materie-Teilchen (AP17)',pt:'Curvas de rotação planas sem partículas de matéria escura (AP17)',nl:'Vlakke rotatiekrommen zonder donkeremateriadeeltjes (AP17)',it:'Curve di rotazione piatte senza particelle di materia oscura (AP17)',zh:'无暗物质粒子的平坦旋转曲线 (AP17)',ja:'ダークマター粒子なしの平坦な回転曲線 (AP17)',ko:'암흑물질 입자 없는 평탄한 회전 곡선 (AP17)',ru:'Плоские кривые вращения без частиц тёмной материи (AP17)',ar:'منحنيات دوران مسطّحة بلا جسيمات مادة مظلمة (AP17)',hi:'गहरे पदार्थ कणों के बिना सपाट घूर्णन वक्र (AP17)'}],
  ['Bell inequality S = 2√2 from structure (AP23)',{es:'Desigualdad de Bell S = 2√2 desde la estructura (AP23)',fr:'Inégalité de Bell S = 2√2 depuis la structure (AP23)',de:'Bell-Ungleichung S = 2√2 aus der Struktur (AP23)',pt:'Desigualdade de Bell S = 2√2 da estrutura (AP23)',nl:'Bell-ongelijkheid S = 2√2 uit de structuur (AP23)',it:'Disuguaglianza di Bell S = 2√2 dalla struttura (AP23)',zh:'贝尔不等式 S = 2√2 源自结构 (AP23)',ja:'ベル不等式 S = 2√2 構造から (AP23)',ko:'벨 부등식 S = 2√2 구조에서 (AP23)',ru:'Неравенство Белла S = 2√2 из структуры (AP23)',ar:'متباينة بل S = 2√2 من البنية (AP23)',hi:'बेल असमिका S = 2√2 संरचना से (AP23)'}],

  // === Three constants line ===
  ['Three constants, three axioms: c ↔ Constraint · ℏ ↔ Break · G ↔ Record',{es:'Tres constantes, tres axiomas: c ↔ Restricción · ℏ ↔ Ruptura · G ↔ Registro',fr:'Trois constantes, trois axiomes : c ↔ Contrainte · ℏ ↔ Brisure · G ↔ Enregistrement',de:'Drei Konstanten, drei Axiome: c ↔ Zwang · ℏ ↔ Bruch · G ↔ Aufzeichnung',pt:'Três constantes, três axiomas: c ↔ Restrição · ℏ ↔ Quebra · G ↔ Registro',nl:'Drie constanten, drie axioma\'s: c ↔ Beperking · ℏ ↔ Breuk · G ↔ Record',it:'Tre costanti, tre assiomi: c ↔ Vincolo · ℏ ↔ Rottura · G ↔ Registrazione',zh:'三个常数，三条公理：c ↔ 约束 · ℏ ↔ 断裂 · G ↔ 记录',ja:'三つの定数、三つの公理：c ↔ 拘束 · ℏ ↔ 破れ · G ↔ 記録',ko:'세 상수, 세 공리: c ↔ 구속 · ℏ ↔ 깨짐 · G ↔ 기록',ru:'Три константы, три аксиомы: c ↔ Ограничение · ℏ ↔ Разрыв · G ↔ Запись',ar:'ثلاثة ثوابت، ثلاث بديهيات: c ↔ قيد · ℏ ↔ كسر · G ↔ سجلّ',hi:'तीन स्थिरांक, तीन स्वयंसिद्ध: c ↔ बाधा · ℏ ↔ टूट · G ↔ अभिलेख'}],
  ['where α = 2 ln(sec ½ + tan ½)',{es:'donde α = 2 ln(sec ½ + tan ½)',fr:'où α = 2 ln(sec ½ + tan ½)',de:'wobei α = 2 ln(sec ½ + tan ½)',pt:'onde α = 2 ln(sec ½ + tan ½)',nl:'waar α = 2 ln(sec ½ + tan ½)',it:'dove α = 2 ln(sec ½ + tan ½)',zh:'其中 α = 2 ln(sec ½ + tan ½)',ja:'ここで α = 2 ln(sec ½ + tan ½)',ko:'여기서 α = 2 ln(sec ½ + tan ½)',ru:'где α = 2 ln(sec ½ + tan ½)',ar:'حيث α = 2 ln(sec ½ + tan ½)',hi:'जहाँ α = 2 ln(sec ½ + tan ½)'}],

  // === KILL SWITCH REGISTRY stats ===
  ['<span class="stat-label">Kill switches</span>',{es:'Interruptores letales',fr:'Interrupteurs de mort',de:'Kill Switches',pt:'Interruptores letais',nl:'Kill switches',it:'Kill switch',zh:'灭杀开关',ja:'キルスイッチ',ko:'킬 스위치',ru:'Переключатели уничтожения',ar:'مفاتيح إيقاف',hi:'किल स्विच'}],
  ['<span class="stat-label">Closed</span>',{es:'Cerrados',fr:'Fermés',de:'Geschlossen',pt:'Fechados',nl:'Gesloten',it:'Chiusi',zh:'已关闭',ja:'閉鎖',ko:'폐쇄',ru:'Закрыты',ar:'مُغلقة',hi:'बंद'}],
  ['<span class="stat-label">Live</span>',{es:'Activos',fr:'Actifs',de:'Aktiv',pt:'Ativos',nl:'Actief',it:'Attivi',zh:'激活',ja:'稼働',ko:'가동',ru:'Активны',ar:'نشطة',hi:'सक्रिय'}],
  ['<span class="stat-label">Non-negotiable</span>',{es:'No negociables',fr:'Non négociables',de:'Nicht verhandelbar',pt:'Inegociáveis',nl:'Niet-onderhandelbaar',it:'Non negoziabili',zh:'不可妥协',ja:'交渉不可',ko:'비협상',ru:'Безусловные',ar:'غير قابلة للتفاوض',hi:'अपरिवर्तनीय'}],

  // === KILL SWITCH REGISTRY rows ===
  ['<span class="result-label">Closed switches</span><span class="result-value">15 formally discharged</span>',{es:'Interruptores cerrados</span><span class="result-value">15 formalmente descargados',fr:'Interrupteurs fermés</span><span class="result-value">15 formellement acquittés',de:'Geschlossene Switches</span><span class="result-value">15 formell entlastet',pt:'Interruptores fechados</span><span class="result-value">15 formalmente dispensados',nl:'Gesloten switches</span><span class="result-value">15 formeel ontslagen',it:'Switch chiusi</span><span class="result-value">15 formalmente scaricati',zh:'已关闭开关</span><span class="result-value">15 个已正式解除',ja:'閉鎖スイッチ</span><span class="result-value">15件 正式解除',ko:'폐쇄 스위치</span><span class="result-value">15개 공식 해제',ru:'Закрытые переключатели</span><span class="result-value">15 формально снятых',ar:'مفاتيح مُغلقة</span><span class="result-value">15 أُعفيت رسميًّا',hi:'बंद स्विच</span><span class="result-value">15 औपचारिक रूप से मुक्त'}],
  ['<span class="result-label">Live — Empirical</span><span class="result-value">Falsifiable by experiment or observation</span>',{es:'Activos — Empíricos</span><span class="result-value">Falsificables por experimento u observación',fr:'Actifs — Empiriques</span><span class="result-value">Falsifiables par expérience ou observation',de:'Aktiv — Empirisch</span><span class="result-value">Durch Experiment oder Beobachtung falsifizierbar',pt:'Ativos — Empíricos</span><span class="result-value">Falsificáveis por experimento ou observação',nl:'Actief — Empirisch</span><span class="result-value">Falsifieerbaar door experiment of observatie',it:'Attivi — Empirici</span><span class="result-value">Falsificabili per esperimento o osservazione',zh:'激活 — 经验性</span><span class="result-value">可通过实验或观测证伪',ja:'稼働 — 経験的</span><span class="result-value">実験または観測で反証可能',ko:'가동 — 경험적</span><span class="result-value">실험 또는 관측으로 반증 가능',ru:'Активные — Эмпирические</span><span class="result-value">Опровержимы экспериментом или наблюдением',ar:'نشطة — تجريبية</span><span class="result-value">قابلة للدحض بالتجربة أو الرصد',hi:'सक्रिय — प्रायोगिक</span><span class="result-value">प्रयोग या अवलोकन से खंडनीय'}],
  ['<span class="result-label">Live — Hard</span><span class="result-value">Falsifiable by theoretical argument</span>',{es:'Activos — Duros</span><span class="result-value">Falsificables por argumento teórico',fr:'Actifs — Durs</span><span class="result-value">Falsifiables par argument théorique',de:'Aktiv — Hart</span><span class="result-value">Durch theoretisches Argument falsifizierbar',pt:'Ativos — Duros</span><span class="result-value">Falsificáveis por argumento teórico',nl:'Actief — Hard</span><span class="result-value">Falsifieerbaar door theoretisch argument',it:'Attivi — Duri</span><span class="result-value">Falsificabili per argomento teorico',zh:'激活 — 硬性</span><span class="result-value">可通过理论论证证伪',ja:'稼働 — 硬性</span><span class="result-value">理論的議論で反証可能',ko:'가동 — 경성</span><span class="result-value">이론적 논증으로 반증 가능',ru:'Активные — Жёсткие</span><span class="result-value">Опровержимы теоретическим аргументом',ar:'نشطة — صلبة</span><span class="result-value">قابلة للدحض بالحجة النظرية',hi:'सक्रिय — कठोर</span><span class="result-value">सैद्धांतिक तर्क से खंडनीय'}],
  ['<span class="result-label">Live — Structural</span><span class="result-value">Rests on an identification that could be shown incorrect</span>',{es:'Activos — Estructurales</span><span class="result-value">Dependen de una identificación que podría demostrarse incorrecta',fr:'Actifs — Structurels</span><span class="result-value">Reposent sur une identification qui pourrait être invalidée',de:'Aktiv — Strukturell</span><span class="result-value">Beruhen auf einer Identifikation, die sich als falsch erweisen könnte',pt:'Ativos — Estruturais</span><span class="result-value">Dependem de uma identificação que pode ser provada incorreta',nl:'Actief — Structureel</span><span class="result-value">Berusten op een identificatie die onjuist zou kunnen blijken',it:'Attivi — Strutturali</span><span class="result-value">Si basano su un\'identificazione che potrebbe rivelarsi errata',zh:'激活 — 结构性</span><span class="result-value">依赖于可能被证明错误的认同',ja:'稼働 — 構造的</span><span class="result-value">誤りと示されうる同定に依拠',ko:'가동 — 구조적</span><span class="result-value">오류로 밝혀질 수 있는 동일시에 의존',ru:'Активные — Структурные</span><span class="result-value">Основаны на отождествлении, которое может быть опровергнуто',ar:'نشطة — بنيوية</span><span class="result-value">تستند إلى تطابق قد يُثبت خطؤه',hi:'सक्रिय — संरचनात्मक</span><span class="result-value">एक पहचान पर निर्भर जो गलत सिद्ध हो सकती है'}],
  ['<span class="result-label">Non-negotiable</span><span class="result-value">6 moral kill switches — if triggered, the architecture is weaponised</span>',{es:'No negociables</span><span class="result-value">6 interruptores morales — si se activan, la arquitectura se convierte en arma',fr:'Non négociables</span><span class="result-value">6 interrupteurs moraux — si déclenchés, l\'architecture est militarisée',de:'Nicht verhandelbar</span><span class="result-value">6 moralische Kill Switches — wenn ausgelöst, wird die Architektur zur Waffe',pt:'Inegociáveis</span><span class="result-value">6 interruptores morais — se acionados, a arquitetura é transformada em arma',nl:'Niet-onderhandelbaar</span><span class="result-value">6 morele kill switches — indien geactiveerd, wordt de architectuur bewapend',it:'Non negoziabili</span><span class="result-value">6 kill switch morali — se attivati, l\'architettura diventa un\'arma',zh:'不可妥协</span><span class="result-value">6个道德灭杀开关——若触发，架构将被武器化',ja:'交渉不可</span><span class="result-value">6つの道徳キルスイッチ——発動すれば構造が兵器化される',ko:'비협상</span><span class="result-value">6개 도덕 킬 스위치 — 작동 시 구조가 무기화됨',ru:'Безусловные</span><span class="result-value">6 моральных переключателей — при срабатывании архитектура превращается в оружие',ar:'غير قابلة للتفاوض</span><span class="result-value">6 مفاتيح أخلاقية — إذا فُعِّلت، تتحول البنية إلى سلاح',hi:'अपरिवर्तनीय</span><span class="result-value">6 नैतिक किल स्विच — यदि सक्रिय हों, तो वास्तुकला शस्त्रीकृत हो जाती है'}],
  ['<span class="result-label">Open debts</span><span class="result-value">4 — cannot be tested until upstream work is complete</span>',{es:'Deudas abiertas</span><span class="result-value">4 — no pueden probarse hasta completar trabajo previo',fr:'Dettes ouvertes</span><span class="result-value">4 — ne peuvent être testées tant que le travail en amont n\'est pas terminé',de:'Offene Schulden</span><span class="result-value">4 — können erst getestet werden, wenn vorgelagerte Arbeit abgeschlossen ist',pt:'Dívidas abertas</span><span class="result-value">4 — não podem ser testadas até a conclusão do trabalho anterior',nl:'Openstaande schulden</span><span class="result-value">4 — kunnen niet getest worden tot het voorliggende werk voltooid is',it:'Debiti aperti</span><span class="result-value">4 — non testabili fino al completamento del lavoro a monte',zh:'未决债务</span><span class="result-value">4个——在上游工作完成前无法测试',ja:'未解決の負債</span><span class="result-value">4件——上流の作業が完了するまでテスト不可',ko:'미결 부채</span><span class="result-value">4개 — 선행 작업 완료 전까지 검증 불가',ru:'Открытые долги</span><span class="result-value">4 — не могут быть проверены до завершения предшествующей работы',ar:'ديون مفتوحة</span><span class="result-value">4 — لا يمكن اختبارها حتى اكتمال العمل السابق',hi:'खुले ऋण</span><span class="result-value">4 — पूर्ववर्ती कार्य पूरा होने तक परीक्षण योग्य नहीं'}],
  ['<span class="result-label">Global kill switch</span><span class="result-value">KS-V.1 — if it fires, everything dies</span>',{es:'Interruptor global</span><span class="result-value">KS-V.1 — si se activa, todo muere',fr:'Interrupteur global</span><span class="result-value">KS-V.1 — s\'il se déclenche, tout meurt',de:'Globaler Kill Switch</span><span class="result-value">KS-V.1 — wenn er auslöst, stirbt alles',pt:'Interruptor global</span><span class="result-value">KS-V.1 — se disparar, tudo morre',nl:'Globale kill switch</span><span class="result-value">KS-V.1 — als hij afgaat, sterft alles',it:'Kill switch globale</span><span class="result-value">KS-V.1 — se scatta, tutto muore',zh:'全局灭杀开关</span><span class="result-value">KS-V.1——若触发，一切消亡',ja:'グローバルキルスイッチ</span><span class="result-value">KS-V.1——発動すればすべてが死ぬ',ko:'글로벌 킬 스위치</span><span class="result-value">KS-V.1 — 작동하면 모든 것이 죽는다',ru:'Глобальный переключатель</span><span class="result-value">KS-V.1 — если сработает, всё гибнет',ar:'مفتاح إيقاف شامل</span><span class="result-value">KS-V.1 — إذا انطلق، يموت كل شيء',hi:'वैश्विक किल स्विच</span><span class="result-value">KS-V.1 — यदि सक्रिय हो, सब कुछ मर जाता है'}],

  // === DOWNLOAD LINK ===
  ['Download the complete Kill Switch Registry',{es:'Descarga el Registro completo de Interruptores Letales',fr:'Télécharger le Registre complet des Interrupteurs de Mort',de:'Das vollständige Kill-Switch-Register herunterladen',pt:'Baixe o Registro completo de Interruptores Letais',nl:'Download het volledige Kill Switch Register',it:'Scarica il Registro completo dei Kill Switch',zh:'下载完整的灭杀开关注册表',ja:'キルスイッチ登録簿の完全版をダウンロード',ko:'킬 스위치 등록부 전체 다운로드',ru:'Скачать полный реестр переключателей уничтожения',ar:'تحميل سجلّ مفاتيح الإيقاف الكامل',hi:'पूर्ण किल स्विच रजिस्ट्री डाउनलोड करें'}],
];

LANGS.forEach(lang => {
  const fp = path.join('C:/Users/info/the420code', lang, 'index.html');
  let h = fs.readFileSync(fp, 'utf8');
  let c = 0;

  for (const [en, translations] of R) {
    const val = translations[lang];
    if (!val) continue;
    // For stat-label and result-label/value entries, reconstruct the full replacement
    if (en.startsWith('<span class="stat-label">')) {
      const newTag = '<span class="stat-label">' + val + '</span>';
      if (h.includes(en)) { h = h.replace(en, newTag); c++; }
    } else if (en.startsWith('<span class="result-label">') && en.includes('result-value')) {
      // Full row replacement
      const newRow = '<span class="result-label">' + val;
      if (h.includes(en)) { h = h.replace(en, newRow); c++; }
    } else if (en.startsWith('<span class="result-label">')) {
      const newTag = '<span class="result-label">' + val + '</span>';
      if (h.includes(en)) { h = h.replace(en, newTag); c++; }
    } else {
      if (h.includes(en)) { h = h.replace(en, val); c++; }
    }
  }

  fs.writeFileSync(fp, h);
  console.log('  ' + lang + ' — ' + c + ' headline changes');
});
console.log('Done');
